nirmata/kyverno-charts

README.md, _config.yaml
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
=> gh-pages: add github page content for helm charts

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
=> adds github action to automate helm chart release

.github/workflows/lint-test.yaml
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
=> changed the naming of the default branch to main

README.md
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
=> fix installation docs url in README

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/templates/cronjob.yaml, charts/kube-bench-adapter/values.yaml
=> new release of kube-bench adapter helm chart with image and job fixes

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/values.yaml
=> updates version of docker image

aws/templates/deployment.yaml, charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/templates/_helpers.tpl, charts/kube-bench-adapter/templates/cronjob.yaml, charts/kube-bench-adapter/templates/secrets.yaml, charts/kube-bench-adapter/values.yaml
=> releases dev helm chart with cron-job policy vioation fixes

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/values.yaml
=> update liveliness and readiness probes

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/values.yaml
=> fixes in probes

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=> bump n4k images version to v1.5.8-n4kbuild.1 release tag

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/values.yaml
=> updates kube-bench tag fixing timestamp issue

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=> bump n4k images version to v1.7.2-n4kbuild.1 release

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=> bump n4k images version to v1.7.4-n4kbuild.1 release

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=>  bump n4k images version to v1.7.5-n4kbuild.1 release

charts/kyverno-operator/Chart.yaml, charts/kyverno-operator/README.md, charts/kyverno-operator/templates/deployment.yaml, charts/kyverno-operator/values.yaml
Need to support http proxies in kyverno operator
=> Fix NDEV-14876 env support for http proxies

charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/templates/deployment.yaml
Fix restricted pod security profile error and reduce the timeout of readiness probe as done for kyverno operator.
=> Fix NDEV-14890 vulnerabilities

charts/kyverno-operator/Chart.yaml, charts/kyverno-operator/README.md, charts/kyverno-operator/templates/deployment.yaml, charts/kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/README.md, charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/README.md
Added the http proxy and custom ca cert support for kyverno operator
Also fixed an incorrect hyphen character in Readmes of Kyverno as well as Venafi adapter.
=> Fix NDEV-14876 and readme typo for other charts

README.md, charts/kyverno-operator/Chart.yaml, charts/kyverno-operator/README.md, charts/nirmata/Chart.yaml, charts/nirmata/README.md
- Updated the README for base, nirmata and kyverno-operator
- Embedded the instructions for installing kyverno-operator as a prerequisite for n4k
- Updated the instructions with the username=nirmata-enterprise-for-kyverno instead of someuser
- Updated some formatting
=> Fix NDEV-15015

aws/Chart.yaml, aws/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml, scripts/aws-marketplace/delivery-options-details.json
Updated the charts with the n4k-1.8.3 version
Performed a sanity test by doing a helm install and validating that kyverno n4k-1.8.3 is getting installed and working fine
=> NDEV-15082: Release enterprise kyverno 1.8.3

charts/image-scan-adapter/Chart.yaml, charts/image-scan-adapter/templates/resource.yaml
I missed this when initially adding the chart.
=> chore: add severity and selectors fields for isacfg 

charts/image-scan-adapter/Chart.yaml, charts/image-scan-adapter/crds/security.nirmata.io_imagescanadapterconfigs.yaml
References [PR #10](https://github.com/nirmata/image-scan-adapter/pull/10) from nirmata/image-scan-adapter.
Fixes [NDEV-15938](https://nirmata.atlassian.net/browse/NDEV-15938).
[NDEV-15938]: https://nirmata.atlassian.net/browse/NDEV-15938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add additional printer columns

charts/image-scan-adapter/Chart.yaml, charts/image-scan-adapter/templates/rbac.yaml
Linked PR: https://github.com/nirmata/image-scan-adapter/pull/12.
=> chore: update rbac

charts/image-scan-adapter/Chart.yaml, charts/image-scan-adapter/crds/security.nirmata.io_imagescanadapterconfigs.yaml
Chart changes for PR https://github.com/nirmata/image-scan-adapter/pull/27.
=> chore: add AGE printer column

aws/values.yaml
Add a missing field that was removed
=> Add missing field

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_helpers.tpl
New kyverno operator image that now handles policyset chart version upgrades, properly (NDEV-16568).
=> fix: new operator image in chart, fixes for NDEV-16568

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml, charts/enterprise-kyverno-operator/values.yaml
Parameterized the repository for pre-delete hook, and also repos for Kyverno cleanup and initimage.
=> fix: allow tuning pre-delete hook image

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/templates/_helpers.tpl, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/values.yaml
Refer: NDEV-16721, NDEV-16722, default namespace excludes, with ability to override
=> exclude Namespaces from Kyverno Webhook

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/templates/_helpers.tpl, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.8/namespace/kyverno.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.9/namespace/kyverno.yaml
- Allow manual creation of kyverno nsp
- Fix regression in getting 1.8.5 to work
=> Ndev 16844 custom kyverno certs

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/crds/adapter.yaml, charts/enterprise-kyverno-operator/crds/policySet.yaml, charts/enterprise-kyverno-operator/crds/security.nirmata.io_kyvernoes.yaml, charts/enterprise-kyverno-operator/templates/_cr-kyverno-helpers.tpl, charts/enterprise-kyverno-operator/templates/clusterrole.yaml, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/templates/cr-policysets.yaml, charts/enterprise-kyverno-operator/templates/imagepullsecret.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml, charts/enterprise-kyverno-operator/templates/secret-for-cr-params.yaml, charts/enterprise-kyverno-operator/templates/secret-for-webhook.yaml, charts/enterprise-kyverno-operator/templates/webhook.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/README.md, charts/nirmata/README.md.gotmpl, charts/nirmata/values.yaml, charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/README.md
=> NDEV-16657 and NDEV-16659

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/templates/_helpers.tpl
* NDEV-16721 exclude namespaces enhanced fix
=> NDEV-16721 enhance exclude namespace fix (#167)

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/templates/_helpers.tpl, charts/kube-bench-adapter/templates/cronjob.yaml, charts/kube-bench-adapter/templates/job.yaml
Adds a job to generate Kube-Bench ClusterPolicyReport on startup.
=> chore(kube-bench): add startup job

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/README.md
=> NDEV-17738 upgrade build with perf fixes 1.10

charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/values.yaml
NDEV-17700
This PR updates the image controller image tag to `0.2.1`
=> feat: update venafi adapter image tag in values.yaml

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/crds/security.nirmata.io_kyvernoes.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/README.md
Upgrade CVE fix from upstream Kyverno fix.
https://nirmata.atlassian.net/browse/NDEV-17865
Sanity check done
=> NDEV-17865-CVE

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_cr-kyverno-helpers.tpl, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Minor fixes for license manager image, sanity test done.
=> Minor fixes

aws/Chart.yaml, scripts/aws-marketplace/delivery-options-details.json, scripts/aws-marketplace/publish-aws-images.sh
Here we are changing the image tags to `v1.10.5-n4k.nirmata.2-aws` and bumped the aws chart version to `v1.12.0-02-aws`
=> change image tag; bump version

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.10/_helpers.tpl, charts/enterprise-kyverno-operator/templates/kyverno-1.10/admission-controller/role.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.10/cleanup-controller/clusterrole.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.10/crds/_helpers.tpl
Cleanup controller role did not get read, watch perms.
=> NDEV-17974 update cleanup controller roles

charts/enterprise-kyverno-operator/Chart.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/_helpers.tpl, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/templates/cleanup-controller/deployment.yaml, charts/nirmata/values.yaml
changes to compliment disableautowebhookgeneration in n4k + CVE free enterprise kyverno operator
=> fixes in charts to accomodate disableautowebhookgeneration

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
change default to false as we want to keep the default behaviour unaltered
=> set default of disableAutoWebhookGeneration to false

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata-stub-crds/Chart.yaml, charts/nirmata-stub-crds/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Upgrade n4k image v1.10.7-n4k.nirmata.1
lm image 0.1.7
kubectl image 1.29.0
=> upgrade n4k, kubectl,lm images

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml
minor correction in enterprise-kyverno-operator
=> correct kubectl image

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml
=> minor correction

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/templates/_helpers.tpl, charts/kube-bench-adapter/values.yaml
Fix https://nirmata.atlassian.net/browse/NDEV-18172, support node selector
=> Support node selector

charts/nirmata/Chart.yaml
Use image with performace changes in 1.11
=> use 1.11 image with performance fixes

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_cr-kyverno-helpers.tpl
https://nirmata.atlassian.net/browse/NDEV-18241
=> Use correct image pull secret

aws/Chart.yaml
=> correct aws chart name

aws/Chart.yaml, scripts/aws-marketplace/publish-aws-chart.sh
chart version correction from v1.12.1 -> 1.12.1
=> correct version

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
=> New charts for visa

charts/nirmata/Chart.yaml
=> correct image for disableautowebhookgeneration

charts/nirmata/Chart.yaml, charts/nirmata/templates/hooks/post-upgrade.yaml, charts/nirmata/values.yaml
=> Policy report cleanup

charts/nirmata/Chart.yaml
=> 3.1.0 release

charts/cluster-registrator/Chart.yaml, charts/cluster-registrator/values.yaml
upgrade cluster registrator image
=> cluster registrator new image

charts/nirmata/Chart.yaml
=> upstream equivalent for dyn webhooks for 1.10

charts/nirmata/Chart.yaml
=> upstream equivalent for dyn webhooks

charts/enterprise-kyverno-operator/Chart.yaml
=> eko 0.2.7-rc1

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/templates/background-controller/service.yaml, charts/nirmata/templates/hooks/pre-delete.yaml, charts/nirmata/values.yaml
FYI, Anushka, upgraded the chart versions from rc*. Only maintained rc on operator chart for now.
=> NDEV-18223 policy violations in pods

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/README.md, charts/kube-bench-adapter/templates/_helpers.tpl, charts/kube-bench-adapter/templates/configmapcustomjob.yaml
Support for multiple cluster-types (job.yamls already present)
Support for custom job file mounted via configmap
=> Ndev 18337 cis gke

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml
new eko image along with kubectl image correction
=> 1.11 fixes

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/post-kyverno-upgrade.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/hooks/post-upgrade.yaml
with nirmata/kubectl we need different set of commands in Jobs.
=> changes to accomodate nirmata/kubectl

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/post-kyverno-upgrade.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/hooks/post-upgrade.yaml
enterprise-kyverno-operator ) k logs -n kyverno po/kyverno-hook-post-upgrade-54dss           Wed Feb 28 17:50:48 2024
sh: awk: not found
sh: syntax error: bad substitution
error with the hook
=> remove awk in hook

charts/cluster-registrator/Chart.yaml, charts/cluster-registrator/README.md, charts/cluster-registrator/templates/job.yaml, charts/cluster-registrator/values.yaml
New version of cluster registrator with support for api key in secret.
=> NDEV-18509 apikey

.github/workflows/release.yaml, charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_cr-kyverno-helpers.tpl, charts/enterprise-kyverno-operator/templates/deployment.yaml, charts/enterprise-kyverno-operator/templates/kyverno-1.9/crds.yaml
See: [NDEV-18547](https://nirmata.atlassian.net/browse/NDEV-18547)
If the image.pullSecrets.create is set to false, then also operator adds a secret to its deployment as well as that of Kyverno. Added checks to not have pullsecrets if that value is false. 
[NDEV-18547]: https://nirmata.atlassian.net/browse/NDEV-18547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Configurable image pull secrets

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_cr-kyverno-helpers.tpl, charts/enterprise-kyverno-operator/templates/deployment.yaml
Same as PR https://github.com/nirmata/kyverno-charts/pull/265, but for Kyverno 1.10
=> support pullsecret suppression if not needed

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/post-kyverno-upgrade.yaml, charts/enterprise-kyverno-operator/values.yaml
=> update post upgrade script

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/values.yaml
https://nirmata.atlassian.net/browse/NDEV-18484
=> add resources field in lm

charts/nirmata/Chart.yaml, charts/nirmata/charts/crds/templates/crds.yaml
Reflecting CRD changes done as part of PR https://github.com/nirmata/kyverno/pull/102/files#diff-eb6df19c8507050878f6dc7cdeaf5babc37001003ee563cedccefa0ba5ffeb91, to kyverno charts.
=> NDEV-18663 configurable TSA crd changes

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/values.yaml
https://nirmata.atlassian.net/browse/NDEV-18484
=> NDEV-18484: resource settings for lm

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml
n4k visa cves as well as polex enhancements
=> fix: VISA CVEs

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/secret-for-cr-params.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/values.yaml
changes for option to take secret for licensekey and apikey
=> feat: add option to take apiKey and licenseKey from secret

charts/cluster-registrator/Chart.yaml, charts/cluster-registrator/templates/job.yaml, charts/cluster-registrator/values.yaml
add an option to disallow the creation of nirmata namespace
=> feat: add option to disable namespace creation in cluster registrator

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/values.yaml
replicate changes for accepting a license key and API key as done in 1.10 recently
=> NDEV-18509: accept license in n4k charts

charts/enterprise-kyverno-operator/Chart.yaml
=> NDEV-18509: 0.4.7

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_helpers.tpl
[Custom Policy Set Ticket](https://nirmata.atlassian.net/browse/NDEV-19034)
Custom Policy sets had to be created manually before but now user is  able to specify a list of extra custom policyset parameters (user, password, version etc.) so that policysets need not be created manually. Added custom policy sets in pre delete hook
=> Added custom policy sets in pre delete hook

aws/Chart.yaml, aws/templates/cleanup/cleanup-admission-reports.yaml, aws/templates/cleanup/cleanup-cluster-admission-reports.yaml
=> aws 1.12.2

.github/workflows/trigger-e2e-test.yaml
this PR introduces a GHA which will trigger the e2e tests action [here]( https://github.com/nirmata/n4k-automation/blob/main/.github/workflows/e2e.yaml ) whenever there will be a release being published.
=> NDEV-18931: added GHA tigger

charts/enterprise-kyverno-operator/Chart.yaml
=> NDEV-19273: updated latest kyverno operator

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml
=> add necessary permission

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/clusterrole.yaml, charts/nirmata/templates/background-controller/clusterrole.yaml, charts/nirmata/templates/cleanup-controller/clusterrole.yaml, charts/nirmata/templates/reports-controller/clusterrole.yaml, charts/nirmata/values.yaml
Back ported the fix that has flags to fix the wild card issues in n4k v1.12 to the version created for eBay in v1.11
[JIRA](https://nirmata.atlassian.net/browse/NDEV-19725)
=> NDEV-19725: ebay wildcard clusterrole fix backport 1.11

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/clusterrole.yaml, charts/nirmata/templates/background-controller/clusterrole.yaml, charts/nirmata/templates/cleanup-controller/clusterrole.yaml, charts/nirmata/templates/reports-controller/clusterrole.yaml
Reverted back the issue in controllers when we set perms in extraResources as null.
=> Fix: Revert the modifications in wildcard-perms feat

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
=> chore: change image reference to reg.nirmata.io

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
This PR introduces new charts for kyverno, which now includes the license-manager image that supports multiarch platforms. This is a rc release.
=> NDEV-20431 : rc charts for kyverno supporting multiarch lm

charts/kube-bench-adapter/Chart.yaml, charts/kube-bench-adapter/templates/_helpers.tpl, charts/kube-bench-adapter/values.yaml
This PR introduces new rc charts for kube-bench adapter which is designed, keeping in mind the NPM-PE requirements.
=> NDEV-20461 : RC charts for kube-bench adapter for NPM-PE

charts/nirmata/Chart.yaml, charts/nirmata/charts/crds/templates/crds.yaml
This PR backports the upstream fix, that allows the mutation of the resources which violates the policies. for n4k-1.11
=> NDEV-20176 :  backport allow changes for preexisting resources that violates policy 1.11

charts/nirmata-kube-controller/.helmignore, charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
Release the initial version for RazorPay demo
=> add nirmata-kube-controller helm chart

charts/nirmata/Chart.yaml, charts/nirmata/templates/cleanup/cleanup-admission-reports.yaml, charts/nirmata/templates/cleanup/cleanup-cluster-admission-reports.yaml, charts/nirmata/templates/hooks/post-upgrade-clean-reports.yaml, charts/nirmata/templates/hooks/pre-delete-scale-to-zero.yaml, charts/nirmata/values.yaml
[JIRA](https://nirmata.atlassian.net/browse/NDEV-20757)
=> NDEV-20757 fix: cleanup cluster admission controller pods went to crashed state

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
update nirmata-kube-controller chart version to 0.1.2
=> NDEV-20686 update nirmata-kube-controller chart version

charts/nirmata/Chart.yaml, charts/nirmata/templates/_helpers.tpl, charts/nirmata/templates/admission-controller/deployment.yaml, charts/nirmata/values.yaml
=> NDEV-20747 : Display the path and the mutations in kyverno-admission-controller logs Add suport in n4k 1.12

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
We want to aggregate cluster roles , therefore we have added a label that implies that this role will aggregate into the view role and cluster role binding is now with the aggregated role.
=> Update nirmata-kube-controller.yaml with aggregated cluster role

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
changed enablePolicyExceptions and enablePolicySets flag to features.policyExceptions.enabled and features.policySets.enabled
added readWriteMode flag which enables nirmata privileged role
=> add readwrite mode

charts/nirmata/Chart.yaml, charts/nirmata/templates/config/disableAutoWebhookGenerationConfigMap.yaml, charts/nirmata/values.yaml
[JIRA](https://nirmata.atlassian.net/browse/NDEV-21094)
=> feat: added disableAutoWebhookGeneration flag in n4k

charts/cloud-controller/templates/scanner/primary-aws-account-config.yaml
Changes the value of metadata: name to "{accountName}-{accountID}"
[JIRA Ticket](https://nirmata.atlassian.net/browse/NDEV-21497)
=> NDEV-21497 : changed metadata name

charts/cloud-controller/policies/ecs/validate-ecs-container-insights-enabled.yaml, charts/cloud-controller/policies/ecs/validate-ecs-containers-nonprivileged.yaml, charts/cloud-controller/policies/ecs/validate-ecs-containers-readonly.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-definition-log-configuration.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-definition-memory-hard-limit.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-definition-nonroot-user.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-definition-pid-mode-check.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-definition-user-for-host-mode-check.yaml, charts/cloud-controller/policies/ecs/validate-ecs-task-public-ip.yaml, charts/cloud-controller/policies/ecs/validate-efs-volume-encryption.yaml, charts/cloud-controller/policies/eks/check-public-access-cidr.yaml, charts/cloud-controller/policies/eks/check-public-endpoint.yaml, charts/cloud-controller/policies/eks/check-secrets-encryption.yaml, charts/cloud-controller/policies/eks/check-supported-k8s-version.yaml, charts/cloud-controller/policies/lambda/check-dead-letter-queue.yaml, charts/cloud-controller/policies/lambda/check-env-var-encryption.yaml, charts/cloud-controller/policies/lambda/check-function-concurrency.yaml, charts/cloud-controller/policies/lambda/check-lambda-runtime.yaml, charts/cloud-controller/policies/lambda/check-lambda-vpc.yaml, charts/cloud-controller/policies/lambda/check-x-ray-tracing-enabled.yaml, charts/cloud-controller/templates/admission-controller/proxy_default.yaml
default proxy template is also changed as part of this PR to cloud-control-point
=> NDEV-21603 changed labels.app to cloud-control-point

.github/workflows/lint-test.yaml, charts/cluster-registrator/Chart.yaml, charts/cluster-registrator/templates/job.yaml, charts/cluster-registrator/templates/secret.yaml, charts/cluster-registrator/values.yaml
[NDEV-21639](https://nirmata.atlassian.net/browse/NDEV-21639)
[NDEV-21657](https://nirmata.atlassian.net/browse/NDEV-21657)
[NDEV-21639]: https://nirmata.atlassian.net/browse/NDEV-21639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDEV-21657]: https://nirmata.atlassian.net/browse/NDEV-21657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NDEV-21639 allow user to add custom image registry, NDEV-21657 secret for tls cert in registrator

charts/nirmata/Chart.yaml
Reverts nirmata/kyverno-charts#538
=> Revert "Configurable reports server storage"

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
add nirmata.io/helm annotation with json object of values.yaml of nirmata-kube-controller
test command:
helm template nirmata-kube-controller ./nirmata-kube-controller \
--set nirmataURL=wss://nirmata.io/tunnels \
--set cluster.name=yun-test-1 \
--set namespace=nirmata \
--set apiToken=0t/QUIJzBKyj9Cq8UKHTBis5sKHvE3RH5teEYkpSkQzXf8VA3NFMzIFBWiCIoUI5CeaE4GNOY3Pxr7N4SB1PAw== \
--set readWriteMode=true
expected annotation in deployment:
annotations:
nirmata.io/namespace: "nirmata"
nirmata.io/cluster-name: "yun-test-1"
nirmata.io/helm: "{\"apiToken\":\"0t/QUIJzBKyj9Cq8UKHTBis5sKHvE3RH5teEYkpSkQzXf8VA3NFMzIFBWiCIoUI5CeaE4GNOY3Pxr7N4SB1PAw==\",\"cluster\":{\"labels\":{},\"name\":\"yun-test-1\",\"type\":\"default-policy-manager-type\"},\"features\":{\"policyExceptions\":{\"enabled\":true},\"polic …
=> add nirmata.io/helm annotation

charts/enterprise-kyverno-operator/Chart.yaml
=> set-policyset-values-empty

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
add feature wise clusterrole and bind them to service account. 
add values field for imagePullSecret in cluster
=> Feature wise clusterrole

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
update permissions for nirmata privileged role to have read only + write policyset + write policy exceptions
=> update permissions for privileged role

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
add secret field in kube controller helm chart
=> Ndev 22528 - add secret field in kube controller

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/custom-ca-configmap.yaml, charts/enterprise-kyverno-operator/templates/deployment.yaml, charts/enterprise-kyverno-operator/values.yaml
add custom CA support in operator
=> add custom CA support in operator

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
add support for custom CA cert and custom CA config map
=> Kube controller custom ca

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
Make resource requests and limits configurable via values.yaml for nirmata-kube-controller and otelagent deployments
=> NDEV-23220:  Make resource requests and limits configurable via values.yaml for nirmata-kube-controller and otelagent deployments

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/imagePullSecret.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
Optimizing Helm Charts for imagePullSecrets
=> Optimizing Helm Charts for imagePullSecrets

charts/cluster-registrator/Chart.yaml, charts/cluster-registrator/templates/job.yaml, charts/cluster-registrator/values.yaml
Reverts nirmata/kyverno-charts#586
=> Revert "feat: add restartPolicy parameter to cluster-registrator chart"

charts/enterprise-kyverno-operator/Chart.yaml
bump app version with health check bug fixes
=> Gh 309 - kyverno health check fixes in operator

charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
disable reports server default installation
=> change reports server default

charts/nirmata/Chart.yaml
GA 1.14 n4k with reports server disabled by default
=> GA 1.14 n4k with reports server disabled by default

charts/nirmata/Chart.yaml, charts/nirmata/templates/NOTES.txt
- updated chart notes
- bump chart version
=> Fix chart notes

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
https://nirmata.atlassian.net/browse/NDEV-23662
=> deprecate: policyexceptions.v2beta1.kyverno.io

charts/reports-server/.helmignore, charts/reports-server/Chart.yaml, charts/reports-server/README.md, charts/reports-server/README.md.gotmpl, charts/reports-server/templates/_helpers.tpl, charts/reports-server/templates/api-service.yaml, charts/reports-server/templates/cluster-roles.yaml, charts/reports-server/templates/database-secret.yaml, charts/reports-server/templates/deployment.yaml, charts/reports-server/templates/etcd.yaml, charts/reports-server/templates/hooks/post-install-api-services.yaml, charts/reports-server/templates/hooks/pre-delete-api-service-cleanup.yaml, charts/reports-server/templates/hpa.yaml, charts/reports-server/templates/namespace.yaml, charts/reports-server/templates/pod-disruption-budget.yaml, charts/reports-server/templates/roles.yaml, charts/reports-server/templates/service-account.yaml, charts/reports-server/templates/service-monitor.yaml, charts/reports-server/templates/service.yaml, charts/reports-server/values.yaml
https://github.com/nirmata/kyverno-charts/issues/649
=> add report-server charts

charts/reports-server/Chart.yaml
This PR syncs the updated Helm chart from `nirmata/reports-server`.
=> Sync chart from nirmata/reports-server

.github/workflows/lint-test.yaml, ct.yaml
- avoids comparing chart bumps against main even for release branches
=> branch specific ct lint

.github/workflows/lint-test.yaml
- removed on push condition
- simplify target branch logic
=> remove push condition

charts/go-agent-remediator/Chart.yaml, charts/go-agent-remediator/crds/serviceagents.nirmata.io_remediators.yaml, charts/go-agent-remediator/crds/serviceagents.nirmata.io_toolconfigs.yaml, charts/go-agent-remediator/templates/rbac.yaml, charts/go-agent-remediator/templates/toolconfig.yaml, charts/go-agent-remediator/values.yaml
This PR syncs the updated Helm chart from `nirmata/go-agent-remediator`.
=> Sync chart from nirmata/go-agent-remediator
