nirmata/kyverno-charts

charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/README.md, charts/venafi-adapter/templates/deployment.yaml, charts/venafi-adapter/values.yaml
Hi,
Supporting a custom CA for venafi adapter by allowing creation of a configmap with a constant key storing that CA and mounting it at a specific location in the pod.
Have not been able to test it though.
=> Fix NDEV-14877 allow customCA

charts/image-scan-adapter/Chart.yaml, charts/image-scan-adapter/templates/deployment.yaml, charts/image-scan-adapter/values.yaml
Provide user with an option to set the resource memory limit in case of OOM killed due to not enough memory.
Quick fix for [NDEV-16129](https://nirmata.atlassian.net/browse/NDEV-16129).
[NDEV-16129]: https://nirmata.atlassian.net/browse/NDEV-16129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: oom killed error

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_helpers.tpl, charts/enterprise-kyverno-operator/values.yaml
* When `pss-restricted` policyset is given, `pss-baseline` should also be included in profiles. 
* Changed the default profile to "prod"
=> Add pss-baseline when pss-restricted is specified to profiles

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/cr-policysets.yaml
Fixed the indentation error in a yaml of the kyverno-policies repo chart, updating that version here.
Also fixed NDEV-16551 regarding including pss-baseline if pss-restricted is provided.
=> fix NDEV-16559 and change pss restricted to include baseline

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml, charts/enterprise-kyverno-operator/values.yaml
- Consolidated default registry settings needed to specify in values.yeml for private registries with pullsecrets. 
- Increased pod memory limit to 256Mb
=> fix: reduce places needing imagepullsecrets settings

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml
We only need kubectl for pre delete hook. Hypercube bundles a lot more. Not needed.
=> Hyperkube to kubectl

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_helpers.tpl, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/values.yaml
* By default, `kyverno`, `kube-system`, `nirmata` & `nirmata-system` are excluded. 
* if `.Values.cloudPlatform` is set to `openshift` then namespaces matching `openshift-*` will be excluded.
=> NDEV-16721, NDEV-16722 exclude Namespaces from Kyverno Webhook. 

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/_helpers.tpl, charts/enterprise-kyverno-operator/templates/cr-policysets.yaml
Empty and "false" check for boolean parameters in helm charts are considered equivalent. That led to an issue in setting the default value of the preventPolicyTamper flag.
Also updated to latest helm chart for kyverno-policies
=> fix boolean value handling in preventPolicyTamper

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml
The enablePolicyExceptions parameter location in Kyverno helm chart had changed. Fixed it.
=> fix: policy exception parameters not being recognized  by operator in 1.10

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/templates/cr-kyverno.yaml, charts/enterprise-kyverno-operator/templates/pre-delete-hook.yaml
Provide string NULLOBJ instead of null due to issues described in the ticket. Also fix a related issue where the pre-delete hook fails if operator chart is installed with podSecurityContext=null.
=> NDEV-17006 support null values in kyverno CR helm section

charts/nirmata/Chart.yaml, charts/nirmata/README.md, charts/nirmata/templates/_helpers.tpl, charts/nirmata/values.yaml
Some labels were applied twice due to being directly as well as indirectly.
Also fixed a couple of minor issues regarding default license key and build (match what operator has).
=> fix: remove duplicate labels

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/README.md, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Update default kyverno build in helm chart for Kyverno 1.9.5 to v1.9.5-n4k.nirmata.4, corresponding to N4K PR https://github.com/nirmata/kyverno/pull/60.
=> NDEV-17828 upgrade n4k with golang cve fix

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/values.yaml, charts/nirmata/Chart.yaml, charts/nirmata/values.yaml
Has new images with CVE fixes updated.
=> CVE release 1.10

charts/enterprise-kyverno-operator/Chart.yaml, charts/enterprise-kyverno-operator/templates/post-kyverno-upgrade.yaml, charts/nirmata/Chart.yaml, charts/nirmata/templates/hooks/post-upgrade.yaml
I still faced issues with substitution
```
nirmata ) k logs -n kyverno po/kyverno-hook-post-upgrade-k46zh                                                                Thu Feb 29 16:31:50 2024
sh: syntax error: bad substitution
```
I suspect it is because the script upstream is written to run in bash and we are running in sh.
I have changed everything that could have caused the substitution issue.
=> change post upgrade

charts/venafi-adapter/Chart.yaml, charts/venafi-adapter/values.yaml
Exposing an environment variable to allow specification of a specific version of venafi pkcs11 client to imagekey controller. The new venafi pkcs11 client version specified has the ability to preserve multiple certificates.
=> NDEV-18668 preserve multiple certs

charts/nirmata/Chart.yaml, charts/nirmata/templates/admission-controller/clusterrole.yaml, charts/nirmata/templates/background-controller/clusterrole.yaml, charts/nirmata/templates/cleanup-controller/clusterrole.yaml, charts/nirmata/templates/reports-controller/clusterrole.yaml
The kyverno admission controller, cleanup controller, reports controller and background controller were crashing unexpectedly upon omitting the wildcard perms in clusterroles of these controllers, this PR aims to fix this issue.
[Jira](https://nirmata.atlassian.net/browse/NDEV-19725)
=> NDEV-19725 : Ebay wildcard clusterrole error fix 1.10

charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
This PR includes the changes - 
1. User helm built-in object Release.Namespace instead of Values.namespace;
2. Remove apiToken example
=> NDEV-20686 remove apiToken example and use Release.Namespace

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/values.yaml
The `apiTokenSecret` field has been removed from the values file as it does not need to be overridden with each deployment.
=> Remove `apiTokenSecret` from Helm values

charts/nirmata/Chart.yaml
This PR releases the GA charts for n4k-1.12.6-n4k.nirmata.3 with the `dumpPatch` flag support added, as well as CVE fixes.
=> NDEV-20747 : GA charts for n4k-1.12.6-n4k.nirmata.3

charts/nirmata/Chart.yaml
This PR is to release GA charts for n4k-1.13 patch release which contains the disableAutoWebhookGeneration flag as well as CVE fixes.
Build is in progress: https://github.com/nirmata/enterprise-kyverno/actions/runs/13050525232
Once build is complete we can merge this PR.
=> GA chart 3.3.4 containing disableAutoWebhookGeneration flag

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
Added option to include cluster labels via helm chart in kube-controller.
Related Jira Ticket :- [JIRA](https://nirmata.atlassian.net/browse/NDEV-21780)
=> NDEV-21780 feat: added option to include cluster labels in kube-controller

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/_helpers.tpl, charts/nirmata-kube-controller/templates/apiTokenSecret.yaml, charts/nirmata-kube-controller/templates/imagePullSecret.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml, charts/nirmata-kube-controller/values.yaml
here is the imagePullSecret being generated when we mention `.Values.global.imageRegistry` `.Values.global.registryUserNmae` and `.Values.global.registryPassword`
```
apiVersion: v1
kind: Secret
metadata:
name: nirmata-controller-registry-secret
namespace: nirmata
type: kubernetes.io/dockerconfigjson
data:
.dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkWE5sY2pwaFpHMXBiZz09In19fQ==
```
=> fix: clusterlabels and included imagePullSecrets and apiTokenSecret

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
The kube-controller deployment can be fetched in operator or kube-controller CR or directly from NCH and it shall have annotations depicting the values overwritten by the user so that we can store this config eventually in NCH to show to the user.
[Detailed design doc](https://docs.google.com/document/d/1mszSfJKnb20i-daE4Y9TD_DQpDaMQx_odwrLtOIvqT0/edit?tab=t.0#heading=h.dlxcok4qhw6l)
=> add annotations to kube controller deployment

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
add read only permission for kube controller deployment in the read only cluster role so that NCH can get the deployment to update featurePermission model
=> add read only permission for kube controller deployment

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
Replaced `exec` probe with `http`
Had to bump chart version to resolve below error:
```
Run ct lint --target-branch main
------------------------------------------------------------------------------------------------------------------------
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
nirmata-kube-controller => (version: "0.2.6", path: "charts/nirmata-kube-controller")
------------------------------------------------------------------------------------------------------------------------
Linting chart 'nirmata-kube-controller => (version: "0.2.6", path: "charts/nirmata-kube-controller")'
Checking chart 'nirmata-kube-controller => (version: "0.2.6", path: "charts/nirmata-kube-controller")' …
```
=> NDEV-20261 | Removed exec probes from go-kube-controller deployment

charts/nirmata-kube-controller/Chart.yaml, charts/nirmata-kube-controller/templates/nirmata-kube-controller.yaml
This PR syncs the updated Helm chart from `nirmata/go-kube-controller`.
=> Sync chart from nirmata/go-kube-controller
